// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiedvxrxzsmtupsdoyui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZWR2eHJ4enNtdHVwc2RveXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzQ3NTksImV4cCI6MjA3MDY1MDc1OX0.IrYG5WIdw4eBctMXG4BVxmVh_-S4taVcLJCzu72CNPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});